#!/usr/bin/env bash
# boot_init.sh — B1 Boot Init (extracted verbatim from AGENTS.md §Boot Sequence · T-212/D1)
# Run at boot step B1: `bash scripts/boot_init.sh`
# Emits: [compact-restore] (if compact today) · active_thread tail · session_tokens · roadmap [/] · CFP_COUNT
#
# ⚠️ KEEP IN SYNC with scripts/compact_reset.py — both implement the same CHAT formula +
#    the consume-once `session_reset=armed→consumed` flip (single-source note · T-180). The sys_fixed BASE constant now lives once in scripts/sys_fixed_base.txt (T-250).
#    Logic internals documented in Implement/07_platform.md §Boot Init.
# ⚠️ compact_state.md fields are `key: value` (COLON = canonical · T-262). Every field read below
#    (dt / compact_size / session_reset) tolerates `[:=]` for back-compat with old `=` files; the
#    consume `sed` writes colon. Format rule single-sourced in Implement/07_platform.md §Boot Init.
# ⚠️ Do NOT remove the LOOP_WEIGHT python normalization (BUG-3 fix) — it forces LW=0 on the
#    in_progress-resume path where neither printf branch fires.

(rm -f .sessions/.cfp_touched 2>/dev/null; cs_dt=$(grep -E "^dt[[:space:]]*[:=]" .sessions/compact_state.md 2>/dev/null | sed -E 's/^dt[[:space:]]*[:=][[:space:]]*//' | cut -d' ' -f1); today=$(date +%Y-%m-%d); compact_restore=false; [ "$cs_dt" = "$today" ] && compact_restore=true && echo "[compact-restore]" && cat .sessions/compact_state.md && echo "---"; phase=$(grep "^phase:" .sessions/active_thread.md 2>/dev/null | awk '{print $2}'); sys_fixed=$(python3 -c "import os; b=int(open('scripts/sys_fixed_base.txt').read().strip()); print(int((os.path.getsize('CLAUDE.md') + os.path.getsize('AGENTS.md'))*0.3) + b)" 2>/dev/null || echo 19500); if [ "$compact_restore" = "true" ]; then cs=$(grep -E "^compact_size[[:space:]]*[:=]" .sessions/compact_state.md 2>/dev/null | sed -E 's/^compact_size[[:space:]]*[:=][[:space:]]*//' || echo "0"); ct=$((sys_fixed + ${cs:-0})); reset_marker=$(grep -E "^session_reset[[:space:]]*[:=]" .sessions/compact_state.md 2>/dev/null | sed -E 's/^session_reset[[:space:]]*[:=][[:space:]]*//' | tr -d ' '); if [ "$reset_marker" = "armed" ]; then printf "SESSION_TOTAL: 0\nCHAT_TOTAL: $ct\nCACHE_READ: 0\nCACHE_WRITE: 0\nTURN_COUNT: 0\nLOOP_WEIGHT: 0\nFILES_READ: 0\nLONG_OUTPUTS: 0\n" > .sessions/session_tokens.md; sed -i '' -E 's/^session_reset[[:space:]]*[:=][[:space:]]*armed/session_reset: consumed/' .sessions/compact_state.md 2>/dev/null || sed -i -E 's/^session_reset[[:space:]]*[:=][[:space:]]*armed/session_reset: consumed/' .sessions/compact_state.md 2>/dev/null; echo "[reset-consumed] SESSION=0 · marker armed→consumed"; else st=$(grep "^SESSION_TOTAL:" .sessions/session_tokens.md 2>/dev/null | awk '{print $2}'); st=${st:-0}; printf "SESSION_TOTAL: $st\nCHAT_TOTAL: $ct\nCACHE_READ: 0\nCACHE_WRITE: 0\nTURN_COUNT: 0\nLOOP_WEIGHT: 0\nFILES_READ: 0\nLONG_OUTPUTS: 0\n" > .sessions/session_tokens.md; echo "[reset-skip] marker=${reset_marker:-absent} · SESSION preserved=$st"; fi; elif [ "$phase" != "in_progress" ]; then printf "SESSION_TOTAL: 0\nCHAT_TOTAL: $sys_fixed\nCACHE_READ: 0\nCACHE_WRITE: 0\nTURN_COUNT: 0\nLOOP_WEIGHT: 0\nFILES_READ: 0\nLONG_OUTPUTS: 0\n" > .sessions/session_tokens.md; fi; [ -f .sessions/session_tokens.md ] && python3 -c "p='.sessions/session_tokens.md';L=[('LOOP_WEIGHT: 0' if x.startswith('LOOP_WEIGHT:') else x) for x in open(p).read().splitlines()];open(p,'w').write(chr(10).join(L)+chr(10))" 2>/dev/null; cat .sessions/active_thread.md 2>/dev/null | tail -4; echo "---"; cat .sessions/session_tokens.md 2>/dev/null; echo "---"; grep -n "\[/\]" docs/master_roadmap.md 2>/dev/null | head -3; echo "---"; echo "CFP_COUNT: $(grep -c '^## CFP-' CODING_FAILURE_PATTERNS.md 2>/dev/null || echo 0)"; echo "---"; python3 scripts/cfp_fix_probe.py 2>/dev/null || true)
