#!/usr/bin/env python3
"""repo_map_check.py — REPO_MAP.md drift detector (T-185).

REPO_MAP.md is a CURATED doc: per-file/dir purpose descriptions are hand-written.
A full regen would destroy them, so this tool DETECTS drift and (optionally) APPENDS
placeholder rows for newly-added items — it NEVER rewrites existing descriptions.

What it compares (top level only):
  documented in REPO_MAP.md   vs   actually present in the repo
    - Root files: rows in the "## Root Files" markdown table  (| `name` | purpose |)
    - Directories: "### `name/`" headers under "## Directories"

Modes:
  python3 scripts/repo_map_check.py            # report drift, exit 0  (Stop-hook default)
  python3 scripts/repo_map_check.py --dry-run  # explicit: report only, never write
  python3 scripts/repo_map_check.py --append   # append placeholder rows/stubs for NEW items only
  python3 scripts/repo_map_check.py --sync     # full auto-sync: rewrite the AUTO structure block
                                               # (folders incl. nested + per-folder file counts),
                                               # carry curated descriptions across content-renames
                                               # (git -M), then append TODO rows for new items.
                                               # Never overwrites curated descriptions. (Stop-hook)

Fail-safe: always exits 0. A detector that crashes a Stop hook is worse than one
that misses a drift (mirrors index_reconcile.py philosophy).
"""

import os
import re
import sys
import argparse
import subprocess
from pathlib import Path
from datetime import date

REPO = Path(__file__).resolve().parent.parent
REPO_MAP = REPO / "REPO_MAP.md"

# top-level entries that should never count as drift (transient / tooling / generated)
IGNORE_DIRS = {".git", "node_modules", "__pycache__", ".next", ".pytest_cache",
               ".venv", "venv", ".idea", ".vscode", ".claude"}
IGNORE_FILES = {".DS_Store"}


def parse_repo_map(text):
    """Return (documented_files:set, documented_dirs:set) from REPO_MAP.md."""
    files, dirs = set(), set()
    # Root files: any `backtick-quoted` token inside the Root Files table region.
    root_region = re.search(r"## Root Files(.*?)(?:\n## |\Z)", text, re.S)
    if root_region:
        for m in re.finditer(r"\|\s*`([^`]+)`\s*\|", root_region.group(1)):
            files.add(m.group(1).strip())
    # Directories: "### `name/`" headers (trailing slash optional in the doc).
    for m in re.finditer(r"^###\s+`([^`]+?)/?`", text, re.M):
        dirs.add(m.group(1).strip().rstrip("/"))
    return files, dirs


def scan_repo():
    """Return (actual_files:set, actual_dirs:set) at the repo top level."""
    actual_files, actual_dirs = set(), set()
    for p in REPO.iterdir():
        if p.name.startswith("._"):
            continue  # macOS AppleDouble metadata (appears on non-native volumes) — always noise
        if p.is_dir():
            # dot-dirs like .agents/ .sessions/ ARE documented, so keep them
            if p.name not in IGNORE_DIRS:
                actual_dirs.add(p.name)
        elif p.is_file():
            # REPO_MAP's Root Files table lists only normal names — skip dotfiles (.gitignore etc.)
            if p.name not in IGNORE_FILES and not p.name.startswith("."):
                actual_files.add(p.name)
    return actual_files, actual_dirs


def compute_drift():
    """Return dict of drift sets (best-effort; never raises)."""
    try:
        text = REPO_MAP.read_text()
    except OSError as exc:
        return {"error": f"cannot read REPO_MAP.md: {exc}"}
    doc_files, doc_dirs = parse_repo_map(text)
    act_files, act_dirs = scan_repo()
    return {
        "new_files":   sorted(act_files - doc_files),   # on disk, not documented
        "new_dirs":    sorted(act_dirs - doc_dirs),
        "stale_files": sorted(doc_files - act_files),    # documented, gone from disk
        "stale_dirs":  sorted(doc_dirs - act_dirs),
        "_text": text,
    }


# --- Recursive structure (user steps 1+2): folders incl nested + per-folder file counts ---
# Facts-only block, fully owned by --sync. Curated prose lives OUTSIDE these markers
# and is never touched. The block is regenerated each sync → idempotent → safe to auto-run.
STRUCT_BEGIN = "<!-- REPO-STRUCTURE:AUTO (generated by repo_map_check.py --sync · do not hand-edit) -->"
STRUCT_END   = "<!-- /REPO-STRUCTURE:AUTO -->"


def scan_repo_recursive():
    """Walk the whole tree (pruning IGNORE_DIRS, skipping ._*/.DS_Store) →
    {rel_dir: {"files": <direct file count>, "subdirs": <child dir count>}}.
    Top level is the key '.'."""
    tree = {}
    for dirpath, dirnames, filenames in os.walk(REPO):
        # prune in-place so os.walk never descends into ignored / AppleDouble dirs
        dirnames[:] = sorted(
            d for d in dirnames
            if d not in IGNORE_DIRS and not d.startswith("._")
        )
        rel = os.path.relpath(dirpath, REPO)
        files = [f for f in filenames
                 if f not in IGNORE_FILES and not f.startswith("._")]
        tree[rel] = {"files": len(files), "subdirs": len(dirnames)}
    return tree


def render_structure_block(tree):
    """Markdown table of every folder (incl nested) with direct file + subfolder
    counts. Fully script-generated — never hand-edited."""
    today = date.today().isoformat()
    lines = [
        STRUCT_BEGIN,
        f"_Auto-generated structure snapshot — repo_map_check.py --sync ({today}). "
        f"Do not hand-edit between these markers; curated descriptions live outside._",
        "",
        "| Folder | Files | Subfolders |",
        "|---|---|---|",
    ]
    for rel in sorted(tree):
        shown = "." if rel == "." else rel
        d = tree[rel]
        lines.append(f"| `{shown}/` | {d['files']} | {d['subdirs']} |")
    lines.append(STRUCT_END)
    return "\n".join(lines)


def sync_structure_block(text, tree):
    """Return text with the AUTO block replaced by a fresh render. If the markers
    are absent, insert the block right after the '## Directories' header (else at
    end of file). Curated text outside the markers is never modified."""
    block = render_structure_block(tree)
    pattern = re.compile(re.escape(STRUCT_BEGIN) + r".*?" + re.escape(STRUCT_END), re.S)
    if pattern.search(text):
        # lambda replacement avoids backslash/backreference surprises in `block`
        return pattern.sub(lambda _m: block, text)
    anchor = re.search(r"^## Directories.*$", text, re.M)
    if anchor:
        idx = anchor.end()
        return text[:idx] + "\n\n" + block + "\n" + text[idx:]
    return text.rstrip() + "\n\n" + block + "\n"


def sync_structure(drift):
    """Rewrite the AUTO structure block to match the live tree (facts only).
    Updates drift['_text'] so a later append step chains off the fresh text."""
    if "error" in drift:
        print(f"[repo-map-skip] {drift['error']} — structure not synced")
        return
    tree = scan_repo_recursive()
    new_text = sync_structure_block(drift["_text"], tree)
    if new_text != drift["_text"]:
        REPO_MAP.write_text(new_text)
        drift["_text"] = new_text
        print(f"[repo-map-sync] structure block updated — {len(tree)} folders mapped")
    else:
        print(f"[repo-map-sync] structure block already current — {len(tree)} folders")


# --- Rename-by-content (user step 3): a rename must read as ONE move, not ---
# delete+add, so the curated description follows the file to its new name.
# Uses git's content-similarity detector (-M) — NOT exact hashing — so a rename
# with a minor edit is still caught. git missing / not a repo / any error → []
# (caller falls back to remove+add: the SAFE direction → new name gets a
# placeholder, old row is flagged stale — nothing silently lost).
def detect_renames():
    """Return [(old, new)] for renamed ROOT files (top level only — that is what
    the curated Root Files table tracks). Empty list on any failure."""
    try:
        out = subprocess.run(
            ["git", "-C", str(REPO), "diff", "--name-status", "-M",
             "--find-renames=50%", "HEAD"],
            capture_output=True, text=True, timeout=10,
        )
        if out.returncode != 0:
            return []
        renames = []
        for line in out.stdout.splitlines():
            parts = line.split("\t")
            # git emits:  R<similarity><TAB>old<TAB>new
            if len(parts) == 3 and parts[0].startswith("R"):
                old, new = parts[1].strip(), parts[2].strip()
                # ROOT files only — a path separator means it lives in a subdir
                if "/" not in old and "/" not in new:
                    renames.append((old, new))
        return renames
    except Exception:
        return []  # fail-safe: a rename we miss degrades to remove+add, never a crash


def carry_renamed_descriptions(text, renames):
    """For each renamed ROOT file with a curated row `| `old` | desc |`, rewrite
    ONLY the backtick NAME token old→new and keep the description prose intact.
    Emits [repo-map-rename] per carried row. Returns (new_text, carried_pairs)
    so the caller can drop carried names from the new/stale drift sets."""
    carried = []
    for old, new in renames:
        # match the name token inside a table cell:  | `old` |   → | `new` |
        pattern = re.compile(r"(\|\s*`)" + re.escape(old) + r"(`\s*\|)")
        new_text, n = pattern.subn(lambda m: m.group(1) + new + m.group(2), text)
        if n:
            text = new_text
            carried.append((old, new))
            print(f"[repo-map-rename] {old} → {new} (carried description, {n} row)")
    return text, carried


def report(drift):
    if "error" in drift:
        print(f"[repo-map-skip] {drift['error']} — skipped (not fatal)")
        return
    lines = []
    for f in drift["new_files"]:
        lines.append(f"[repo-map-drift] new root file not in REPO_MAP.md: {f} — document it (run --append for a placeholder)")
    for d in drift["new_dirs"]:
        lines.append(f"[repo-map-drift] new top-level dir not in REPO_MAP.md: {d}/ — document it (run --append for a placeholder)")
    for f in drift["stale_files"]:
        lines.append(f"[repo-map-drift] stale root file in REPO_MAP.md (gone from disk): {f} — remove or update the row")
    for d in drift["stale_dirs"]:
        lines.append(f"[repo-map-drift] stale dir in REPO_MAP.md (gone from disk): {d}/ — remove or update the section")
    if lines:
        for ln in lines:
            print(ln)
    else:
        print("[repo-map-clean] REPO_MAP.md matches the repo top level")
    return lines


def append_placeholders(drift):
    """Append placeholder rows/stubs for NEW items only. Existing curated
    descriptions are never touched. Stale items are reported, never deleted."""
    if "error" in drift:
        print(f"[repo-map-skip] {drift['error']} — nothing appended")
        return
    text = drift["_text"]
    today = date.today().isoformat()
    added = 0

    # New root files → append rows to the end of the "## Root Files" table.
    if drift["new_files"]:
        root = re.search(r"(## Root Files.*?)(\n## |\Z)", text, re.S)
        if root:
            block = root.group(1).rstrip()
            rows = "".join(
                f"\n| `{f}` | _(TODO: describe — auto-added {today} by repo_map_check)_ |"
                for f in drift["new_files"]
            )
            text = text[:root.start(1)] + block + rows + text[root.end(1):]
            added += len(drift["new_files"])

    # New dirs → append "### `dir/`" stub sections at the end of the file.
    if drift["new_dirs"]:
        stubs = "".join(
            f"\n\n### `{d}/`\n_(TODO: describe — auto-added {today} by repo_map_check)_"
            for d in drift["new_dirs"]
        )
        text = text.rstrip() + stubs + "\n"
        added += len(drift["new_dirs"])

    if added:
        REPO_MAP.write_text(text)
        print(f"[repo-map-append] added {added} placeholder entr(y/ies) → REPO_MAP.md "
              f"(fill in the real descriptions · existing rows untouched)")
        if drift["stale_files"] or drift["stale_dirs"]:
            print("[repo-map-append] note: stale entries were NOT removed (judgment — review manually)")
    else:
        print("[repo-map-clean] nothing new to append")


def main():
    ap = argparse.ArgumentParser(description="Detect REPO_MAP.md drift vs repo top level")
    ap.add_argument("--dry-run", action="store_true", help="report only, never write (default behavior)")
    ap.add_argument("--append", action="store_true", help="append placeholder rows/stubs for NEW items only")
    ap.add_argument("--sync", action="store_true", help="auto-sync structure block (folders + per-folder file counts) — never overwrites curated descriptions")
    args = ap.parse_args()

    try:
        drift = compute_drift()
        if args.sync and not args.dry_run:
            report(drift)
            # S2: carry curated descriptions across renames BEFORE the structure
            # block is rebuilt, so the fresh text already reflects the new names.
            renames = detect_renames()
            if renames:
                new_text, carried = carry_renamed_descriptions(drift["_text"], renames)
                if new_text != drift["_text"]:
                    REPO_MAP.write_text(new_text)
                    drift["_text"] = new_text
                # carried rows now document the new names → drop them from the
                # drift sets so append_placeholders doesn't double-add a TODO row.
                for old, new in carried:
                    if new in drift["new_files"]:
                        drift["new_files"].remove(new)
                    if old in drift["stale_files"]:
                        drift["stale_files"].remove(old)
            sync_structure(drift)        # S1: structure block
            append_placeholders(drift)   # S3: TODO rows for genuinely-new items only
        elif args.append and not args.dry_run:
            report(drift)
            append_placeholders(drift)
        else:
            report(drift)
    except Exception as exc:  # fail-safe: never abort a Stop hook
        print(f"[repo-map-skip] unexpected error: {exc} — skipped (not fatal)")
    sys.exit(0)


if __name__ == "__main__":
    main()
