#!/usr/bin/env python3
"""
session_analyzer.py — Cross-session pattern detection.
Reads knowledge/index_sessions.json, finds repeated action/friction patterns.
Pattern appears ≥3 times → flag as promotion candidate.

Usage:
  python3 scripts/session_analyzer.py [--dry-run] [--seed]
"""

import json
import sys
from collections import defaultdict
from datetime import date
from pathlib import Path

ROOT = Path(__file__).parent.parent
INDEX_PATH = ROOT / "knowledge" / "index_sessions.json"
PROMOTIONS_PATH = ROOT / ".sessions" / "promotions.md"
THRESHOLD = 3

PROMOTIONS_HEADER = (
    "# Session Promotion Candidates\n"
    "Generated by scripts/session_analyzer.py\n\n"
    "| skill | pattern | count | type | first_seen | last_updated |\n"
    "|-------|---------|-------|------|------------|---------------|\n"
)


def load_sessions():
    if not INDEX_PATH.exists():
        return []
    try:
        data = json.loads(INDEX_PATH.read_text(encoding="utf-8"))
        if isinstance(data, list):
            return data
        return []
    except (json.JSONDecodeError, OSError):
        return []


def detect_patterns(sessions):
    # action_counts[(skill, action)] = set of session paths
    action_sessions = defaultdict(set)
    friction_sessions = defaultdict(set)

    for entry in sessions:
        if not isinstance(entry, dict):
            continue
        skill = entry.get("skill") or "unknown"
        path = entry.get("path") or id(entry)

        actions = entry.get("actions") or []
        if isinstance(actions, list):
            for action in actions:
                if action:
                    action_sessions[(skill, str(action))].add(path)

        friction = entry.get("friction") or []
        if isinstance(friction, list):
            for event in friction:
                if event:
                    friction_sessions[(skill, str(event))].add(path)

    action_patterns = [
        {"skill": k[0], "action": k[1], "count": len(v)}
        for k, v in action_sessions.items()
    ]
    friction_patterns = [
        {"skill": k[0], "friction": k[1], "count": len(v)}
        for k, v in friction_sessions.items()
    ]

    return (
        sorted(action_patterns, key=lambda x: -x["count"]),
        sorted(friction_patterns, key=lambda x: -x["count"]),
    )


def print_report(action_patterns, friction_patterns):
    print("=== Session Pattern Analyzer ===")
    print()

    has_any = False

    candidates_a = [p for p in action_patterns if p["count"] >= THRESHOLD]
    print("Action patterns (skill | action | count | recommend)")
    if candidates_a:
        has_any = True
        for p in candidates_a:
            print(f"  {p['skill']} | {p['action']} | {p['count']} | promote")
    else:
        print("  (none above threshold)")

    print()

    candidates_f = [p for p in friction_patterns if p["count"] >= THRESHOLD]
    print("Friction patterns (skill | friction | count | recommend)")
    if candidates_f:
        has_any = True
        for p in candidates_f:
            print(f"  {p['skill']} | {p['friction']} | {p['count']} | promote")
    else:
        print("  (none above threshold)")

    if not has_any:
        print()
        print("No patterns yet.")


def load_existing_promotions():
    if not PROMOTIONS_PATH.exists():
        return set()
    try:
        text = PROMOTIONS_PATH.read_text(encoding="utf-8")
    except OSError:
        return set()
    existing = set()
    for line in text.splitlines():
        if line.startswith("|") and not line.startswith("| skill") and not line.startswith("|---"):
            parts = [p.strip() for p in line.strip("|").split("|")]
            if len(parts) >= 2:
                existing.add((parts[0], parts[1]))
    return existing


def seed_promotions(action_patterns, friction_patterns):
    today = date.today().isoformat()
    existing = load_existing_promotions()

    new_rows = []
    for p in action_patterns:
        if p["count"] >= THRESHOLD:
            key = (p["skill"], p["action"])
            if key not in existing:
                new_rows.append(
                    f"| {p['skill']} | {p['action']} | {p['count']} | action | {today} | {today} |"
                )
    for p in friction_patterns:
        if p["count"] >= THRESHOLD:
            key = (p["skill"], p["friction"])
            if key not in existing:
                new_rows.append(
                    f"| {p['skill']} | {p['friction']} | {p['count']} | friction | {today} | {today} |"
                )

    if not new_rows:
        print("No new promotion candidates to seed.")
        return

    PROMOTIONS_PATH.parent.mkdir(parents=True, exist_ok=True)
    if not PROMOTIONS_PATH.exists():
        PROMOTIONS_PATH.write_text(PROMOTIONS_HEADER, encoding="utf-8")

    with PROMOTIONS_PATH.open("a", encoding="utf-8") as f:
        for row in new_rows:
            f.write(row + "\n")

    print(f"Seeded {len(new_rows)} new candidate(s) to {PROMOTIONS_PATH}")


def main():
    args = sys.argv[1:]
    seed_mode = "--seed" in args

    sessions = load_sessions()
    action_patterns, friction_patterns = detect_patterns(sessions)

    if seed_mode:
        seed_promotions(action_patterns, friction_patterns)
    else:
        print_report(action_patterns, friction_patterns)


if __name__ == "__main__":
    main()
